# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W9ZN1xWXEKNgwZuwnuzKocoBKPcYkgdI
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/content/Bank Customer Churn Prediction 1.csv")

df

df.info()

df.isnull().sum() # here i can not found any null values

df.drop(['customer_id'], axis=1, inplace=True)

df.value_counts(['country'])

df[df.duplicated()]

from sklearn.preprocessing import LabelEncoder

df['country']=LabelEncoder().fit_transform(df['country'])

df['gender']=LabelEncoder().fit_transform(df['gender'])

df

df['country'].value_counts()

x = df.drop(['churn'], axis=1)
y = df['churn']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=42)

X_train.shape

from sklearn.preprocessing import StandardScaler

std=StandardScaler()

x_train=std.fit_transform(X_train)
x_test=std.transform(X_test)

from sklearn.linear_model import LogisticRegression

cls = LogisticRegression()

cls.fit(x_train, y_train)

cls.score(X_test, y_test)

X_test.shape

new_customer_data_dict = {
    'credit_score': [700],
    'country': [0],
    'gender': [1],
    'age': [45],
    'tenure': [5],
    'balance': [100000.00],
    'products_number': [2],
    'credit_card': [1],
    'active_member': [1],
    'estimated_salary': [90000.00]
}

new_customer_data = pd.DataFrame(new_customer_data_dict)

new_customer_data = new_customer_data[x.columns]

new_customer_data

scaled_new_customer_data = std.transform(new_customer_data)

churn_prediction = cls.predict(scaled_new_customer_data)

churn_prediction

print(f"The predicted churn value for the new customer is: {churn_prediction[0]}")

from sklearn.metrics import confusion_matrix

y_pred=cls.predict(X_test)

confusion_matrix  = confusion_matrix(y_test, y_pred)

confusion_matrix

